# レディース
lady = Category.create(text: "レディース")
lady_1 = lady.children.create(text: "トップス")
lady_1.children.create([{text: "Tシャツ/カットソー(半袖/袖なし)"},{text: "Tシャツ/カットソー(七分/長袖)"},{text: "シャツ/ブラウス(半袖/袖なし)"},{text: "シャツ/ブラウス(七分/長袖)"},{text: "ポロシャツ"},{text: "キャミソール"},{text: "タンクトップ"},{text: "ホルターネック"},{text: "ニット/セーター"},{text: "チュニック"},{text: "カーディガン/ボレロ"},{text: "アンサンブル"},{text: "ベスト/ジレ"},{text: "パーカー"},{text: "トレーナー/スウェット"},{text: "ベアトップ/チューブトップ"},{text: "ジャージ"},{text: "その他"}])
lady_2 = lady.children.create(text: "ジャケット/アウター")
lady_2.children.create([{text: "テーラードジャケット"},{text: "ノーカラージャケット"},{text: "Gジャン/デニムジャケット"},{text: "レザージャケット"},{text: "ダウンジャケット"},{text: "ライダースジャケット"},{text: "ミリタリージャケット"},{text: "ダウンベスト"},{text: "ジャンパー/ブルゾン"},{text: "ポンチョ"},{text: "ロングコート"},{text: "トレンチコート"},{text: "ダッフルコート"},{text: "ピーコート"},{text: "チェスターコート"},{text: "モッズコート"},{text: "スタジャン"},{text: "毛皮/ファーコート"},{text: "スプリングコート"},{text: "スカジャン"},{text: "その他"}])
lady_3 = lady.children.create(text: "パンツ")
lady_3.children.create([{text: "デニム/ジーンズ"},{text: "ショートパンツ"},{text: "カジュアルパンツ"},{text: "ハーフパンツ"},{text: "チノパン"},{text: "ワークパンツ/カーゴパンツ"},{text: "クロップドパンツ"},{text: "サロペット/オーバーオール"},{text: "オールインワン"},{text: "サルエルパンツ"},{text: "ガウチョパンツ"},{text: "その他"}])
lady_4 = lady.children.create(text: "スカート")
lady_4.children.create([{text: "ミニスカート"},{text: "ひざ丈スカート"},{text: "ロングスカート"},{text: "キュロット"},{text: "その他"}])
lady_5 = lady.children.create(text: "ワンピース")
lady_5.children.create([{text: "ミニワンピース"},{text: "ひざ丈ワンピース"},{text: "ロングワンピース"},{text: "その他"}])
lady_6 = lady.children.create(text: "靴")
lady_6.children.create([{text: "ハイヒール/パンプス"},{text: "ブーツ"},{text: "サンダル"},{text: "スニーカー"},{text: "ミュール"},{text: "モカシン"},{text: "ローファー/革靴"},{text: "フラットシューズ/バレエシューズ"},{text: "長靴/レインシューズ"},{text: "その他"}])
lady_7 = lady.children.create(text: "ルームウェア/パジャマ")
lady_7.children.create([{text: "パジャマ"},{text: "ルームウェア"}])
lady_8 = lady.children.create(text: "レッグウェア")
lady_8.children.create([{text: "ソックス"},{text: "スパッツ/レギンス"},{text: "ストッキング/タイツ"},{text: "レッグウォーマー"},{text: "その他"}])
lady_9 = lady.children.create(text: "帽子")
lady_9.children.create([{text: "ニットキャップ/ビーニー"},{text: "ハット"},{text: "ハンチング/ベレー帽"},{text: "キャップ"},{text: "キャスケット"},{text: "麦わら帽子"},{text: "その他"}])
lady_10 = lady.children.create(text: "バッグ")
lady_10.children.create([{text: "ハンドバッグ"},{text: "トートバッグ"},{text: "エコバッグ"},{text: "リュック/バックパック"},{text: "ボストンバッグ"},{text: "スポーツバッグ"},{text: "ショルダーバッグ"},{text: "クラッチバッグ"},{text: "ポーチ/バニティ"},{text: "ボディバッグ/ウェストバッグ"},{text: "マザーズバッグ"},{text: "メッセンジャーバッグ"},{text: "ビジネスバッグ"},{text: "旅行用バッグ/キャリーバッグ"},{text: "ショップ袋"},{text: "和装用バッグ"},{text: "かごバッグ"},{text: "その他"}])
lady_11 = lady.children.create(text: "アクセサリー")
lady_11.children.create([{text: "ネックレス"},{text: "ブレスレット"},{text: "バングル/リストバンド"},{text: "リング"},{text: "ピアス(片耳用)"},{text: "ピアス(両耳用)"},{text: "イヤリング"},{text: "アンクレット"},{text: "ブローチ/コサージュ"},{text: "チャーム"},{text: "その他"}])
lady_12 = lady.children.create(text: "ヘアアクセサリー")
lady_12.children.create([{text: "ヘアゴム/シュシュ"},{text: "ヘアバンド/カチューシャ"},{text: "ヘアピン"},{text: "その他"}])
lady_13 = lady.children.create(text: "小物")
lady_13.children.create([{text: "長財布"},{text: "折り財布"},{text: "コインケース/小銭入れ"},{text: "名刺入れ/定期入れ"},{text: "キーケース"},{text: "キーホルダー"},{text: "手袋/アームカバー"},{text: "ハンカチ"},{text: "ベルト"},{text: "マフラー/ショール"},{text: "ストール/スヌード"},{text: "バンダナ/スカーフ"},{text: "ネックウォーマー"},{text: "サスペンダー"},{text: "サングラス/メガネ"},{text: "モバイルケース/カバー"},{text: "手帳"},{text: "イヤマフラー"},{text: "傘"},{text: "レインコート/ポンチョ"},{text: "ミラー"},{text: "タバコグッズ"},{text: "その他"}])
lady_14 = lady.children.create(text: "時計")
lady_14.children.create([{text: "腕時計(アナログ)"},{text: "腕時計(デジタル)"},{text: "ラバーベルト"},{text: "レザーベルト"},{text: "金属ベルト"},{text: "その他"}])
lady_15 = lady.children.create(text: "ウィッグ/エクステ")
lady_15.children.create([{text: "前髪ウィッグ"},{text: "ロングストレート"},{text: "ロングカール"},{text: "ショートストレート"},{text: "ショートカール"},{text: "その他"}])
lady_16 = lady.children.create(text: "浴衣/水着")
lady_16.children.create([{text: "浴衣"},{text: "着物"},{text: "振袖"},{text: "長襦袢/半襦袢"},{text: "水着セパレート"},{text: "水着ワンピース"},{text: "水着スポーツ用"},{text: "その他"}])
lady_17 = lady.children.create(text: "スーツ/フォーマル/ドレス")
lady_17.children.create([{text: "スカートスーツ上下"},{text: "パンツスーツ上下"},{text: "ドレス"},{text: "パーティーバッグ"},{text: "シューズ"},{text: "ウェディング"},{text: "その他"}])
lady_18 = lady.children.create(text: "マタニティ")
lady_18.children.create([{text: "トップス"},{text: "アウター"},{text: "インナー"},{text: "ワンピース"},{text: "パンツ/スパッツ"},{text: "スカート"},{text: "パジャマ"},{text: "授乳服"},{text: "その他"}])
lady_19 = lady.children.create(text: "その他")
lady_19.children.create([{text: "コスプレ"},{text: "下着"},{text: "その他"}])

# メンズ
men = Category.create(text: "メンズ")
men_1 = men.children.create(text: "トップス")
men_1.children.create([{text: "Tシャツ/カットソー(半袖/袖なし)"},{text: "Tシャツ/カットソー(七分/長袖)"},{text: "シャツ"},{text: "ポロシャツ"},{text: "タンクトップ"},{text: "ニット/セーター"},{text: "パーカー"},{text: "カーディガン"},{text: "スウェット"},{text: "ジャージ"},{text: "ベスト"},{text: "その他"}])
men_2 = men.children.create(text: "ジャケット/アウター")
men_2.children.create([{text: "テーラードジャケット"},{text: "ノーカラージャケット"},{text: "Gジャン/デニムジャケット"},{text: "レザージャケット"},{text: "ダウンジャケット"},{text: "ライダースジャケット"},{text: "ミリタリージャケット"},{text: "ナイロンジャケット"},{text: "フライトジャケット"},{text: "ダッフルコート"},{text: "ピーコート"},{text: "ステンカラーコート"},{text: "トレンチコート"},{text: "モッズコート"},{text: "チェスターコート"},{text: "スタジャン"},{text: "スカジャン"},{text: "ブルゾン"},{text: "マウンテンパーカー"},{text: "ダウンベスト"},{text: "ポンチョ"},{text: "カバーオール"},{text: "その他"}])
men_3 = men.children.create(text: "パンツ")
men_3.children.create([{text: "デニム/ジーンズ"},{text: "ワークパンツ/カーゴパンツ"},{text: "スラックス"},{text: "チノパン"},{text: "ショートパンツ"},{text: "ペインターパンツ"},{text: "サルエルパンツ"},{text: "オーバーオール"},{text: "その他"}])
men_4 = men.children.create(text: "靴")
men_4.children.create([{text: "スニーカー"},{text: "サンダル"},{text: "ブーツ"},{text: "モカシン"},{text: "ドレス/ビジネス"},{text: "長靴/レインシューズ"},{text: "デッキシューズ"},{text: "その他"}])
men_5 = men.children.create(text: "バッグ")
men_5.children.create([{text: "ショルダーバッグ"},{text: "トートバッグ"},{text: "ボストンバッグ"},{text: "リュック/バックパック"},{text: "ウエストポーチ"},{text: "ボディーバッグ"},{text: "ドラムバッグ"},{text: "ビジネスバッグ"},{text: "トラベルバッグ"},{text: "メッセンジャーバッグ"},{text: "エコバッグ"},{text: "その他"}])
men_6 = men.children.create(text: "スーツ")
men_6.children.create([{text: "スーツジャケット"},{text: "スーツベスト"},{text: "スラックス"},{text: "セットアップ"},{text: "その他"}])
men_7 = men.children.create(text: "帽子")
men_7.children.create([{text: "キャップ"},{text: "ハット"},{text: "ニットキャップ/ビーニー"},{text: "ハンチング/ベレー帽"},{text: "キャスケット"},{text: "サンバイザー"},{text: "その他"}])
men_8 = men.children.create(text: "アクセサリー")
men_8.children.create([{text: "ネックレス"},{text: "ブレスレット"},{text: "バングル/リストバンド"},{text: "リング"},{text: "ピアス(片耳用)"},{text: "ピアス(両耳用)"},{text: "アンクレット"},{text: "その他"}])
men_9 = men.children.create(text: "小物")
men_9.children.create([{text: "長財布"},{text: "折り財布"},{text: "マネークリップ"},{text: "コインケース/小銭入れ"},{text: "名刺入れ/定期入れ"},{text: "キーケース"},{text: "キーホルダー"},{text: "ネクタイ"},{text: "手袋"},{text: "ハンカチ"},{text: "ベルト"},{text: "マフラー"},{text: "ストール"},{text: "バンダナ"},{text: "ネックウォーマー"},{text: "サスペンダー"},{text: "ウォレットチェーン"},{text: "サングラス/メガネ"},{text: "モバイルケース/カバー"},{text: "手帳"},{text: "ストラップ"},{text: "ネクタイピン"},{text: "カフリンクス"},{text: "イヤマフラー"},{text: "傘"},{text: "レインコート"},{text: "ミラー"},{text: "タバコグッズ"},{text: "その他"}])
men_10 = men.children.create(text: "時計")
men_10.children.create([{text: "腕時計(アナログ)"},{text: "腕時計(デジタル)"},{text: "ラバーベルト"},{text: "レザーベルト"},{text: "金属ベルト"},{text: "その他"}])
men_11 = men.children.create(text: "水着")
men_11.children.create([{text: "一般水着"},{text: "スポーツ用"},{text: "アクセサリー"},{text: "その他"}])
men_12 = men.children.create(text: "レッグウェア")
men_12.children.create([{text: "ソックス"},{text: "レギンス/スパッツ"},{text: "レッグウォーマー"},{text: "その他"}])
men_13 = men.children.create(text: "アンダーウェア")
men_13.children.create([{text: "トランクス"},{text: "ボクサーパンツ"},{text: "その他"}])
men_14 = men.children.create(text: "その他")
men_14.children.create([{text: "すべて"}])

# ベビー・キッズ
baby_kids = Category.create(text: "ベビー・キッズ")
baby_kids_1 = baby_kids.children.create(text: "ベビー服(女の子用) ~95cm")
baby_kids_1.children.create([{text: "トップス"},{text: "アウター"},{text: "パンツ"},{text: "スカート"},{text: "ワンピース"},{text: "ベビードレス"},{text: "おくるみ"},{text: "下着/肌着"},{text: "パジャマ"},{text: "ロンパース"},{text: "その他"}])
baby_kids_2 = baby_kids.children.create(text: "ベビー服(男の子用) ~95cm")
baby_kids_2.children.create([{text: "トップス"},{text: "アウター"},{text: "パンツ"},{text: "おくるみ"},{text: "下着/肌着"},{text: "パジャマ"},{text: "ロンパース"},{text: "その他"}])
baby_kids_3 = baby_kids.children.create(text: "ベビー服(男女兼用) ~95cm")
baby_kids_3.children.create([{text: "トップス"},{text: "アウター"},{text: "パンツ"},{text: "おくるみ"},{text: "下着/肌着"},{text: "パジャマ"},{text: "ロンパース"},{text: "その他"}])
baby_kids_4 = baby_kids.children.create(text: "キッズ服(女の子用) 100cm~")
baby_kids_4.children.create([{text: "コート"},{text: "ジャケット/上着"},{text: "トップス(Tシャツ/カットソー)"},{text: "トップス(トレーナー)"},{text: "トップス(チュニック)"},{text: "トップス(タンクトップ)"},{text: "トップス(その他)"},{text: "スカート"},{text: "パンツ"},{text: "ワンピース"},{text: "セットアップ"},{text: "パジャマ"},{text: "フォーマル/ドレス"},{text: "和服"},{text: "浴衣"},{text: "甚平"},{text: "水着"},{text: "その他"}])
baby_kids_5 = baby_kids.children.create(text: "キッズ服(男の子用) 100cm~")
baby_kids_5.children.create([{text: "コート"},{text: "ジャケット/上着"},{text: "トップス(Tシャツ/カットソー)"},{text: "トップス(トレーナー)"},{text: "トップス(その他)"},{text: "パンツ"},{text: "セットアップ"},{text: "パジャマ"},{text: "フォーマル/ドレス"},{text: "和服"},{text: "浴衣"},{text: "甚平"},{text: "水着"},{text: "その他"}])
baby_kids_6 = baby_kids.children.create(text: "キッズ服(男女兼用) 100cm~")
baby_kids_6.children.create([{text: "コート"},{text: "ジャケット/上着"},{text: "トップス(Tシャツ/カットソー)"},{text: "トップス(トレーナー)"},{text: "トップス(その他)"},{text: "ボトムス"},{text: "パジャマ"},{text: "その他"}])
baby_kids_7 = baby_kids.children.create(text: "キッズ靴")
baby_kids_7.children.create([{text: "スニーカー"},{text: "サンダル"},{text: "ブーツ"},{text: "長靴"},{text: "その他"}])
baby_kids_8 = baby_kids.children.create(text: "子ども用ファッション小物")
baby_kids_8.children.create([{text: "靴下/スパッツ"},{text: "帽子"},{text: "エプロン"},{text: "サスペンダー"},{text: "タイツ"},{text: "ハンカチ"},{text: "バンダナ"},{text: "ベルト"},{text: "マフラー"},{text: "傘"},{text: "手袋"},{text: "スタイ"},{text: "バッグ"},{text: "その他"}])
baby_kids_9 = baby_kids.children.create(text: "おむつ/トイレ/バス")
baby_kids_9.children.create([{text: "おむつ用品"},{text: "おまる/補助便座"},{text: "トレーニングパンツ"},{text: "ベビーバス"},{text: "お風呂用品"},{text: "その他"}])
baby_kids_10 = baby_kids.children.create(text: "外出/移動用品")
baby_kids_10.children.create([{text: "ベビーカー"},{text: "抱っこひも/スリング"},{text: "チャイルドシート"},{text: "その他"}])
baby_kids_11 = baby_kids.children.create(text: "授乳/食事")
baby_kids_11.children.create([{text: "ミルク"},{text: "ベビーフード"},{text: "ベビー用食器"},{text: "その他"}])
baby_kids_12 = baby_kids.children.create(text: "ベビー家具/寝具/室内用品")
baby_kids_12.children.create([{text: "ベッド"},{text: "布団/毛布"},{text: "イス"},{text: "たんす"},{text: "その他"}])
baby_kids_13 = baby_kids.children.create(text: "おもちゃ")
baby_kids_13.children.create([{text: "おふろのおもちゃ"},{text: "がらがら"},{text: "オルゴール"},{text: "ベビージム"},{text: "手押し車/カタカタ"},{text: "知育玩具"},{text: "その他"}])
baby_kids_14 = baby_kids.children.create(text: "行事/記念品")
baby_kids_14.children.create([{text: "お宮参り用品"},{text: "お食い初め用品"},{text: "アルバム"},{text: "手形/足形"},{text: "その他"}])
baby_kids_15 = baby_kids.children.create(text: "その他")
baby_kids_15.children.create([{text: "母子手帳用品"},{text: "その他"}])

# インテリア・住まい・小物
interior_residence_accessory = Category.create(text: "インテリア・住まい・小物")
interior_residence_accessory_1 = interior_residence_accessory.children.create(text: "キッチン/食器")
interior_residence_accessory_1.children.create([{text: "食器"},{text: "調理器具"},{text: "収納/キッチン雑貨"},{text: "弁当用品"},{text: "カトラリー(スプーン等)"},{text: "テーブル用品"},{text: "容器"},{text: "エプロン"},{text: "アルコールグッズ"},{text: "浄水機"},{text: "その他"}])
interior_residence_accessory_2 = interior_residence_accessory.children.create(text: "ベッド/マットレス")
interior_residence_accessory_2.children.create([{text: "セミシングルベッド"},{text: "シングルベッド"},{text: "セミダブルベッド"},{text: "ダブルベッド"},{text: "ワイドダブルベッド"},{text: "クイーンベッド"},{text: "キングベッド"},{text: "脚付きマットレスベッド"},{text: "マットレス"},{text: "すのこベッド"},{text: "ロフトベッド/システムベッド"},{text: "簡易ベッド/折りたたみベッド"},{text: "収納付き"},{text: "その他"}])
interior_residence_accessory_3 = interior_residence_accessory.children.create(text: "ソファ/ソファベッド")
interior_residence_accessory_3.children.create([{text: "ソファセット"},{text: "シングルソファ"},{text: "ラブソファ"},{text: "トリプルソファ"},{text: "オットマン"},{text: "コーナーソファ"},{text: "ビーズソファ/クッションソファ"},{text: "ローソファ/フロアソファ"},{text: "ソファベッド"},{text: "応接セット"},{text: "ソファカバー"},{text: "リクライニングソファ"},{text: "その他"}])
interior_residence_accessory_4 = interior_residence_accessory.children.create(text: "椅子/チェア")
interior_residence_accessory_4.children.create([{text: "一般"},{text: "スツール"},{text: "ダイニングチェア"},{text: "ハイバックチェア"},{text: "ロッキングチェア"},{text: "座椅子"},{text: "折り畳みイス"},{text: "デスクチェア"},{text: "その他"}])
interior_residence_accessory_5 = interior_residence_accessory.children.create(text: "机/テーブル")
interior_residence_accessory_5.children.create([{text: "こたつ"},{text: "カウンターテーブル"},{text: "サイドテーブル"},{text: "センターテーブル"},{text: "ダイニングテーブル"},{text: "座卓/ちゃぶ台"},{text: "アウトドア用"},{text: "パソコン用"},{text: "事務机/学習机"},{text: "その他"}])
interior_residence_accessory_6 = interior_residence_accessory.children.create(text: "収納家具")
interior_residence_accessory_6.children.create([{text: "リビング収納"},{text: "キッチン収納"},{text: "玄関/屋外収納"},{text: "バス/トイレ収納"},{text: "本収納"},{text: "本/CD/DVD収納"},{text: "洋服タンス/押入れ収納"},{text: "電話台/ファックス台"},{text: "ドレッサー/鏡台"},{text: "棚/ラック"},{text: "ケース/ボックス"},{text: "その他"}])
interior_residence_accessory_7 = interior_residence_accessory.children.create(text: "ラグ/カーペット/マット")
interior_residence_accessory_7.children.create([{text: "ラグ"},{text: "カーペット"},{text: "ホットカーペット"},{text: "玄関/キッチンマット"},{text: "トイレ/バスマット"},{text: "その他"}])
interior_residence_accessory_8 = interior_residence_accessory.children.create(text: "カーテン/ブラインド")
interior_residence_accessory_8.children.create([{text: "カーテン"},{text: "ブラインド"},{text: "ロールスクリーン"},{text: "のれん"},{text: "その他"}])
interior_residence_accessory_9 = interior_residence_accessory.children.create(text: "ライト/照明")
interior_residence_accessory_9.children.create([{text: "蛍光灯/電球"},{text: "天井照明"},{text: "フロアスタンド"},{text: "その他"}])
interior_residence_accessory_10 = interior_residence_accessory.children.create(text: "寝具")
interior_residence_accessory_10.children.create([{text: "布団/毛布"},{text: "枕"},{text: "シーツ/カバー"},{text: "その他"}])
interior_residence_accessory_11 = interior_residence_accessory.children.create(text: "インテリア小物")
interior_residence_accessory_11.children.create([{text: "ごみ箱"},{text: "ウェルカムボード"},{text: "オルゴール"},{text: "クッション"},{text: "クッションカバー"},{text: "スリッパラック"},{text: "ティッシュボックス"},{text: "バスケット/かご"},{text: "フォトフレーム"},{text: "マガジンラック"},{text: "モビール"},{text: "モビール"},{text: "花瓶"},{text: "灰皿"},{text: "傘立て"},{text: "小物入れ"},{text: "置時計"},{text: "掛時計/柱時計"},{text: "鏡(立て掛け式)"},{text: "鏡(壁掛け式)"},{text: "置物"},{text: "風鈴"},{text: "植物/観葉植物"},{text: "その他"}])
interior_residence_accessory_12 = interior_residence_accessory.children.create(text: "季節/年中行事")
interior_residence_accessory_12.children.create([{text: "正月"},{text: "成人式"},{text: "バレンタインデー"},{text: "ひな祭り"},{text: "子どもの日"},{text: "母の日"},{text: "父の日"},{text: "父の日"},{text: "サマーギフト/お中元"},{text: "夏/夏休み"},{text: "ハロウィン"},{text: "敬老の日"},{text: "七五三"},{text: "お歳暮"},{text: "クリスマス"},{text: "冬一般"},{text: "その他"}])
interior_residence_accessory_13 = interior_residence_accessory.children.create(text: "その他")
interior_residence_accessory_13.children.create([{text: "すべて"}])

# 本・音楽・ゲーム
book_music_game = Category.create(text: "本・音楽・ゲーム")
book_music_game_1 = book_music_game.children.create(text: "本")
book_music_game_1.children.create([{text: "文学/小説"},{text: "人文/社会"},{text: "ノンフィクション/教養"},{text: "地図/旅行ガイド"},{text: "ビジネス/経済"},{text: "ビジネス/経済"},{text: "健康/医学"},{text: "コンピュータ/IT"},{text: "趣味/スポーツ/実用"},{text: "住まい/暮らし/子育て"},{text: "アート/エンタメ"},{text: "洋書"},{text: "絵本"},{text: "参考書"},{text: "その他"}])
book_music_game_2 = book_music_game.children.create(text: "漫画")
book_music_game_2.children.create([{text: "全巻セット"},{text: "少年漫画"},{text: "少女漫画"},{text: "青年漫画"},{text: "女性漫画"},{text: "同人誌"},{text: "その他"}])
book_music_game_3 = book_music_game.children.create(text: "雑誌")
book_music_game_3.children.create([{text: "アート/エンタメ/ホビー"},{text: "ファッション"},{text: "ニュース/総合"},{text: "趣味/スポーツ"},{text: "その他"}])
book_music_game_4 = book_music_game.children.create(text: "CD")
book_music_game_4.children.create([{text: "邦楽"},{text: "洋楽"},{text: "アニメ"},{text: "クラシック"},{text: "K-POP/アジア"},{text: "キッズ/ファミリー"},{text: "その他"}])
book_music_game_5 = book_music_game.children.create(text: "DVD/ブルーレイ")
book_music_game_5.children.create([{text: "外国映画"},{text: "日本映画"},{text: "アニメ"},{text: "TVドラマ"},{text: "ミュージック"},{text: "お笑い/バラエティ"},{text: "スポーツ/フィットネス"},{text: "キッズ/ファミリー"},{text: "その他"}])
book_music_game_6 = book_music_game.children.create(text: "レコード")
book_music_game_6.children.create([{text: "邦楽"},{text: "洋楽"},{text: "その他"}])
book_music_game_7 = book_music_game.children.create(text: "テレビゲーム")
book_music_game_7.children.create([{text: "家庭用ゲーム本体"},{text: "家庭用ゲームソフト"},{text: "携帯用ゲーム本体"},{text: "携帯用ゲームソフト"},{text: "PCゲーム"},{text: "その他"}])

# おもちゃ・ホビー・グッズ
toy_hobby_goods = Category.create(text: "おもちゃ・ホビー・グッズ")
toy_hobby_goods_1 = toy_hobby_goods.children.create(text: "おもちゃ")
toy_hobby_goods_1.children.create([{text: "キャラクターグッズ"},{text: "ぬいぐるみ"},{text: "小物/アクセサリー"},{text: "模型/プラモデル"},{text: "ミニカー"},{text: "トイラジコン"},{text: "プラモデル"},{text: "ホビーラジコン"},{text: "鉄道模型"},{text: "その他"}])
toy_hobby_goods_2 = toy_hobby_goods.children.create(text: "タレントグッズ")
toy_hobby_goods_2.children.create([{text: "アイドル"},{text: "ミュージシャン"},{text: "タレント/お笑い芸人"},{text: "スポーツ選手"},{text: "その他"}])
toy_hobby_goods_3 = toy_hobby_goods.children.create(text: "コミック/アニメグッズ")
toy_hobby_goods_3.children.create([{text: "ストラップ"},{text: "キーホルダー"},{text: "バッジ"},{text: "カード"},{text: "クリアファイル"},{text: "ポスター"},{text: "タオル"},{text: "その他"}])
toy_hobby_goods_4 = toy_hobby_goods.children.create(text: "トレーディングカード")
toy_hobby_goods_4.children.create([{text: "遊戯王"},{text: "マジック：ザ・ギャザリング"},{text: "ポケモンカードゲーム"},{text: "デュエルマスターズ"},{text: "バトルスピリッツ"},{text: "プリパラ"},{text: "アイカツ"},{text: "カードファイト!! ヴァンガード"},{text: "ヴァイスシュヴァルツ"},{text: "プロ野球オーナーズリーグ"},{text: "ベースボールヒーローズ"},{text: "ドラゴンボール"},{text: "スリーブ"},{text: "その他"}])
toy_hobby_goods_5 = toy_hobby_goods.children.create(text: "フィギュア")
toy_hobby_goods_5.children.create([{text: "コミック/アニメ"},{text: "特撮"},{text: "ゲームキャラクター"},{text: "SF/ファンタジー/ホラー"},{text: "アメコミ"},{text: "スポーツ"},{text: "ミリタリー"},{text: "その他"}])
toy_hobby_goods_6 = toy_hobby_goods.children.create(text: "楽器/器材")
toy_hobby_goods_6.children.create([{text: "エレキギター"},{text: "アコースティックギター"},{text: "ベース"},{text: "エフェクター"},{text: "アンプ"},{text: "弦楽器"},{text: "管楽器"},{text: "鍵盤楽器"},{text: "打楽器"},{text: "和楽器"},{text: "楽譜/スコア"},{text: "レコーディング/PA機器"},{text: "DJ機器"},{text: "DTM/DAW"},{text: "その他"}])
toy_hobby_goods_7 = toy_hobby_goods.children.create(text: "コレクション")
toy_hobby_goods_7.children.create([{text: "武具"},{text: "使用済切手/官製はがき"},{text: "旧貨幣/金貨/銀貨/記念硬貨"},{text: "印刷物"},{text: "ノベルティグッズ"},{text: "その他"}])
toy_hobby_goods_8 = toy_hobby_goods.children.create(text: "ミリタリー")
toy_hobby_goods_8.children.create([{text: "トイガン"},{text: "個人装備"},{text: "その他"}])
toy_hobby_goods_9 = toy_hobby_goods.children.create(text: "美術品")
toy_hobby_goods_9.children.create([{text: "陶芸"},{text: "ガラス"},{text: "漆芸"},{text: "金属工芸"},{text: "絵画/タペストリ"},{text: "版画"},{text: "彫刻/オブジェクト"},{text: "書"},{text: "写真"},{text: "その他"}])
toy_hobby_goods_10 = toy_hobby_goods.children.create(text: "アート用品")
toy_hobby_goods_10.children.create([{text: "画材"},{text: "額縁"},{text: "その他"}])
toy_hobby_goods_11 = toy_hobby_goods.children.create(text: "その他")
toy_hobby_goods_11.children.create([{text: "トランプ/UNO"},{text: "カルタ/百人一首"},{text: "ダーツ"},{text: "ビリヤード"},{text: "麻雀"},{text: "パズル/ジグソーパズル"},{text: "囲碁/将棋"},{text: "オセロ/チェス"},{text: "人生ゲーム"},{text: "野球/サッカーゲーム"},{text: "スポーツ"},{text: "三輪車/乗り物"},{text: "ヨーヨー"},{text: "模型製作用品"},{text: "鉄道"},{text: "航空機"},{text: "アマチュア無線"},{text: "パチンコ/パチスロ"},{text: "その他"}])

# コスメ・香水・美容
cosme_perfume_beauty = Category.create(text: "コスメ・香水・美容")
cosme_perfume_beauty_1 = cosme_perfume_beauty.children.create(text: "ベースメイク")
cosme_perfume_beauty_1.children.create([{text: "ファンデーション"},{text: "化粧下地"},{text: "コントロールカラー"},{text: "BBクリーム"},{text: "CCクリーム"},{text: "コンシーラー"},{text: "フェイスパウダー"},{text: "トライアルセット/サンプル"},{text: "その他"}])
cosme_perfume_beauty_2 = cosme_perfume_beauty.children.create(text: "メイクアップ")
cosme_perfume_beauty_2.children.create([{text: "アイシャドウ"},{text: "口紅"},{text: "リップグロス"},{text: "リップライナー"},{text: "チーク"},{text: "フェイスカラー"},{text: "マスカラ"},{text: "アイライナー"},{text: "つけまつげ"},{text: "アイブロウペンシル"},{text: "パウダーアイブロウ"},{text: "眉マスカラ"},{text: "トライアルセット/サンプル"},{text: "メイク道具/化粧小物"},{text: "美顔用品/美顔ローラー"},{text: "その他"}])
cosme_perfume_beauty_3 = cosme_perfume_beauty.children.create(text: "ネイルケア")
cosme_perfume_beauty_3.children.create([{text: "ネイルカラー"},{text: "カラージェル"},{text: "ネイルベースコート/トップコート"},{text: "ネイルアート用品"},{text: "ネイルパーツ"},{text: "ネイルチップ/付け爪"},{text: "手入れ用具"},{text: "除光液"},{text: "その他"}])
cosme_perfume_beauty_4 = cosme_perfume_beauty.children.create(text: "香水")
cosme_perfume_beauty_4.children.create([{text: "香水(女性用)"},{text: "香水(男性用)"},{text: "ユニセックス"},{text: "ボディミスト"},{text: "その他"}])
cosme_perfume_beauty_5 = cosme_perfume_beauty.children.create(text: "スキンケア/基礎化粧品")
cosme_perfume_beauty_5.children.create([{text: "化粧水/ローション"},{text: "乳液/ミルク"},{text: "美容液"},{text: "フェイスクリーム"},{text: "洗顔料"},{text: "クレンジング/メイク落とし"},{text: "パック/フェイスマスク"},{text: "ジェル/ゲル"},{text: "ブースター/導入液"},{text: "アイケア"},{text: "リップケア"},{text: "トライアルセット/サンプル"},{text: "洗顔グッズ"},{text: "その他"}])
cosme_perfume_beauty_6 = cosme_perfume_beauty.children.create(text: "ヘアケア")
cosme_perfume_beauty_6.children.create([{text: "シャンプー"},{text: "トリートメント"},{text: "コンディショナー"},{text: "リンス"},{text: "スタイリング剤"},{text: "カラーリング剤"},{text: "ブラシ"},{text: "その他"}])
cosme_perfume_beauty_7 = cosme_perfume_beauty.children.create(text: "ボディケア")
cosme_perfume_beauty_7.children.create([{text: "オイル/クリーム"},{text: "ハンドクリーム"},{text: "ローション"},{text: "日焼け止め/サンオイル"},{text: "ボディソープ"},{text: "入浴剤"},{text: "制汗/デオドラント"},{text: "フットケア"},{text: "その他"}])
cosme_perfume_beauty_8 = cosme_perfume_beauty.children.create(text: "オーラルケア")
cosme_perfume_beauty_8.children.create([{text: "口臭防止/エチケット用品"},{text: "歯ブラシ"},{text: "その他"}])
cosme_perfume_beauty_9 = cosme_perfume_beauty.children.create(text: "リラクゼーション")
cosme_perfume_beauty_9.children.create([{text: "エッセンシャルオイル"},{text: "芳香器"},{text: "お香/香炉"},{text: "キャンドル"},{text: "リラクゼーショングッズ"},{text: "その他"}])
cosme_perfume_beauty_10 = cosme_perfume_beauty.children.create(text: "ダイエット")
cosme_perfume_beauty_10.children.create([{text: "ダイエット食品"},{text: "エクササイズ用品"},{text: "体重計"},{text: "体脂肪計"},{text: "その他"}])
cosme_perfume_beauty_11 = cosme_perfume_beauty.children.create(text: "その他")
cosme_perfume_beauty_11.children.create([{text: "健康用品"},{text: "看護/介護用品"},{text: "救急/衛生用品"},{text: "その他"}])

# 家電・スマホ・カメラ
appliance_smartphone_camera = Category.create(text: "家電・スマホ・カメラ")
appliance_smartphone_camera_1 = appliance_smartphone_camera.children.create(text: "スマートフォン/携帯電話")
appliance_smartphone_camera_1.children.create([{text: "スマートフォン本体"},{text: "バッテリー/充電器"},{text: "携帯電話本体"},{text: "PHS本体"},{text: "その他"}])
appliance_smartphone_camera_2 = appliance_smartphone_camera.children.create(text: "スマホアクセサリー")
appliance_smartphone_camera_2.children.create([{text: "Android用ケース"},{text: "iPhone用ケース"},{text: "カバー"},{text: "イヤホンジャック"},{text: "ストラップ"},{text: "フィルム"},{text: "自撮り棒"},{text: "その他"}])
appliance_smartphone_camera_3 = appliance_smartphone_camera.children.create(text: "PC/タブレット")
appliance_smartphone_camera_3.children.create([{text: "タブレット"},{text: "ノートPC"},{text: "デスクトップ型PC"},{text: "ディスプレイ"},{text: "電子ブックリーダー"},{text: "PC周辺機器"},{text: "PCパーツ"},{text: "その他"}])
appliance_smartphone_camera_4 = appliance_smartphone_camera.children.create(text: "カメラ")
appliance_smartphone_camera_4.children.create([{text: "デジタルカメラ"},{text: "ビデオカメラ"},{text: "レンズ(単焦点)"},{text: "レンズ(ズーム)"},{text: "フィルムカメラ"},{text: "防犯カメラ"},{text: "その他"}])
appliance_smartphone_camera_5 = appliance_smartphone_camera.children.create(text: "テレビ/映像機器")
appliance_smartphone_camera_5.children.create([{text: "テレビ"},{text: "プロジェクター"},{text: "ブルーレイレコーダー"},{text: "DVDレコーダー"},{text: "ブルーレイプレーヤー"},{text: "DVDプレーヤー"},{text: "映像用ケーブル"},{text: "その他"}])
appliance_smartphone_camera_6 = appliance_smartphone_camera.children.create(text: "オーディオ機器")
appliance_smartphone_camera_6.children.create([{text: "ポータブルプレーヤー"},{text: "イヤフォン"},{text: "ヘッドフォン"},{text: "アンプ"},{text: "スピーカー"},{text: "ケーブル/シールド"},{text: "ラジオ"},{text: "その他"}])
appliance_smartphone_camera_7 = appliance_smartphone_camera.children.create(text: "美容/健康")
appliance_smartphone_camera_7.children.create([{text: "ヘアドライヤー"},{text: "ヘアアイロン"},{text: "美容機器"},{text: "電気シェーバー"},{text: "電動歯ブラシ"},{text: "その他"}])
appliance_smartphone_camera_8 = appliance_smartphone_camera.children.create(text: "冷暖房/空調")
appliance_smartphone_camera_8.children.create([{text: "エアコン"},{text: "空気清浄器"},{text: "加湿器"},{text: "扇風機"},{text: "除湿機"},{text: "ファンヒーター"},{text: "電気ヒーター"},{text: "オイルヒーター"},{text: "ストーブ"},{text: "ホットカーペット"},{text: "こたつ"},{text: "電気毛布"},{text: "その他"}])
appliance_smartphone_camera_9 = appliance_smartphone_camera.children.create(text: "生活家電")
appliance_smartphone_camera_9.children.create([{text: "冷蔵庫"},{text: "洗濯機"},{text: "炊飯器"},{text: "電子レンジ/オーブン"},{text: "調理機器"},{text: "アイロン"},{text: "掃除機"},{text: "エスプレッソマシン"},{text: "コーヒーメーカー"},{text: "衣類乾燥機"},{text: "その他"}])
appliance_smartphone_camera_10 = appliance_smartphone_camera.children.create(text: "その他")
appliance_smartphone_camera_10.children.create([{text: "その他"}])
# スポーツ・レジャー
sport_leisure = Category.create(text: "スポーツ・レジャー")
sport_leisure_1 = sport_leisure.children.create(text: "ゴルフ")
sport_leisure_1.children.create([{text: "クラブ"},{text: "ウエア(男性用)"},{text: "ウエア(女性用)"},{text: "バッグ"},{text: "シューズ(男性用)"},{text: "シューズ(女性用)"},{text: "アクセサリー"},{text: "その他"}])
sport_leisure_2 = sport_leisure.children.create(text: "フィッシング")
sport_leisure_2.children.create([{text: "ロッド"},{text: "リール"},{text: "ルアー用品"},{text: "ウエア"},{text: "釣り糸/ライン"},{text: "その他"}])
sport_leisure_3 = sport_leisure.children.create(text: "自転車")
sport_leisure_3.children.create([{text: "自転車本体"},{text: "ウエア"},{text: "パーツ"},{text: "アクセサリー"},{text: "バッグ"},{text: "工具/メンテナンス"},{text: "その他"}])
sport_leisure_4 = sport_leisure.children.create(text: "トレーニング/エクササイズ")
sport_leisure_4.children.create([{text: "ランニング"},{text: "ウォーキング"},{text: "ヨガ"},{text: "トレーニング用品"},{text: "その他"}])
sport_leisure_5 = sport_leisure.children.create(text: "野球")
sport_leisure_5.children.create([{text: "ウェア"},{text: "シューズ"},{text: "グローブ"},{text: "バット"},{text: "アクセサリー"},{text: "防具"},{text: "練習機器"},{text: "記念グッズ"},{text: "応援グッズ"},{text: "その他"}])
sport_leisure_6 = sport_leisure.children.create(text: "サッカー/フットサル")
sport_leisure_6.children.create([{text: "ウェア"},{text: "シューズ"},{text: "ボール"},{text: "アクセサリー"},{text: "記念グッズ"},{text: "応援グッズ"},{text: "その他"}])
sport_leisure_7 = sport_leisure.children.create(text: "テニス")
sport_leisure_7.children.create([{text: "ラケット(硬式用)"},{text: "ラケット(軟式用)"},{text: "ウェア"},{text: "シューズ"},{text: "ボール"},{text: "アクセサリー"},{text: "記念グッズ"},{text: "応援グッズ"},{text: "その他"}])
sport_leisure_8 = sport_leisure.children.create(text: "スノーボード")
sport_leisure_8.children.create([{text: "ボード"},{text: "バインディング"},{text: "ブーツ(男性用)"},{text: "ブーツ(女性用)"},{text: "ブーツ(子ども用)"},{text: "ウエア/装備(男性用)"},{text: "ウエア/装備(女性用)"},{text: "ウエア/装備(子ども用)"},{text: "アクセサリー"},{text: "バッグ"},{text: "その他"}])
sport_leisure_9 = sport_leisure.children.create(text: "スキー")
sport_leisure_9.children.create([{text: "板"},{text: "ブーツ(男性用)"},{text: "ブーツ(女性用)"},{text: "ブーツ(子ども用)"},{text: "ビンディング"},{text: "ウエア(男性用)"},{text: "ウエア(女性用)"},{text: "ウエア(子ども用)"},{text: "ストック"},{text: "その他"}])
sport_leisure_10 = sport_leisure.children.create(text: "その他スポーツ")
sport_leisure_10.children.create([{text: "ダンス/バレエ"},{text: "サーフィン"},{text: "バスケットボール"},{text: "バドミントン"},{text: "バレーボール"},{text: "スケートボード"},{text: "陸上競技"},{text: "ラグビー"},{text: "アメリカンフットボール"},{text: "ボクシング"},{text: "ボウリング"},{text: "その他"}])
sport_leisure_11 = sport_leisure.children.create(text: "アウトドア")
sport_leisure_11.children.create([{text: "テント/タープ"},{text: "ライト/ランタン"},{text: "寝袋/寝具"},{text: "テーブル/チェア"},{text: "ストーブ/コンロ"},{text: "調理器具"},{text: "食器"},{text: "登山用品"},{text: "その他"}])
sport_leisure_12 = sport_leisure.children.create(text: "その他")
sport_leisure_12.children.create([{text: "旅行用品"},{text: "その他"}])

# ハンドメイド
handmade = Category.create(text: "ハンドメイド")
handmade_1 = handmade.children.create(text: "アクセサリー(女性用)")
handmade_1.children.create([{text: "ピアス"},{text: "イヤリング"},{text: "ネックレス"},{text: "ブレスレット"},{text: "リング"},{text: "チャーム"},{text: "ヘアゴム"},{text: "アンクレット"},{text: "その他"}])
handmade_2 = handmade.children.create(text: "ファッション/小物")
handmade_2.children.create([{text: "バッグ(女性用)"},{text: "バッグ(男性用)"},{text: "財布(女性用)"},{text: "財布(男性用)"},{text: "ファッション雑貨"},{text: "その他"}])
handmade_3 = handmade.children.create(text: "アクセサリー/時計")
handmade_3.children.create([{text: "アクセサリー(男性用)"},{text: "時計(女性用)"},{text: "時計(男性用)"},{text: "その他"}])
handmade_4 = handmade.children.create(text: "日用品/インテリア")
handmade_4.children.create([{text: "キッチン用品"},{text: "家具"},{text: "文房具"},{text: "アート/写真"},{text: "アロマ/キャンドル"},{text: "フラワー/ガーデン"},{text: "その他"}])
handmade_5 = handmade.children.create(text: "趣味/おもちゃ")
handmade_5.children.create([{text: "クラフト/布製品"},{text: "おもちゃ/人形"},{text: "その他"}])
handmade_6 = handmade.children.create(text: "キッズ/ベビー")
handmade_6.children.create([{text: "ファッション雑貨"},{text: "スタイ/よだれかけ"},{text: "外出用品"},{text: "ネームタグ"},{text: "その他"}])
handmade_7 = handmade.children.create(text: "素材/材料")
handmade_7.children.create([{text: "各種パーツ"},{text: "生地/糸"},{text: "型紙/パターン"},{text: "その他"}])
handmade_8 = handmade.children.create(text: "二次創作物")
handmade_8.children.create([{text: "Ingress"},{text: "クリエイターズ宇宙兄弟"},{text: "その他"},{text: "チケット"},{text: "すべて"}])
handmade_9 = handmade.children.create(text: "その他")
handmade_9.children.create([{text: "すべて"}])

# チケット
ticket = Category.create(text: "チケット")
ticket_1 = ticket.children.create(text: "音楽")
ticket_1.children.create([{text: "男性アイドル"},{text: "女性アイドル"},{text: "韓流"},{text: "国内アーティスト"},{text: "海外アーティスト"},{text: "音楽フェス"},{text: "声優/アニメ"},{text: "その他"}])
ticket_2 = ticket.children.create(text: "スポーツ")
ticket_2.children.create([{text: "サッカー"},{text: "野球"},{text: "テニス"},{text: "格闘技/プロレス"},{text: "相撲/武道"},{text: "ゴルフ"},{text: "バレーボール"},{text: "バスケットボール"},{text: "モータースポーツ"},{text: "ウィンタースポーツ"},{text: "その他"}])
ticket_3 = ticket.children.create(text: "演劇/芸能")
ticket_3.children.create([{text: "ミュージカル"},{text: "演劇"},{text: "伝統芸能"},{text: "落語"},{text: "お笑い"},{text: "オペラ"},{text: "サーカス"},{text: "バレエ"},{text: "その他"}])
ticket_4 = ticket.children.create(text: "イベント")
ticket_4.children.create([{text: "声優/アニメ"},{text: "キッズ/ファミリー"},{text: "トークショー/講演会"},{text: "その他"}])
ticket_5 = ticket.children.create(text: "映画")
ticket_5.children.create([{text: "邦画"},{text: "洋画"},{text: "その他"}])
ticket_6 = ticket.children.create(text: "施設利用券")
ticket_6.children.create([{text: "遊園地/テーマパーク"},{text: "美術館/博物館"},{text: "スキー場"},{text: "ゴルフ場"},{text: "フィットネスクラブ"},{text: "プール"},{text: "ボウリング場"},{text: "水族館"},{text: "動物園"},{text: "その他"}])
ticket_7 = ticket.children.create(text: "優待券/割引券")
ticket_7.children.create([{text: "ショッピング"},{text: "レストラン/食事券"},{text: "フード/ドリンク券"},{text: "宿泊券"},{text: "その他"}])
ticket_8 = ticket.children.create(text: "その他")
ticket_8.children.create([{text: "すべて"}])


# 自動車・オートバイ
car_motorcycle = Category.create(text: "自動車・オートバイ")
car_motorcycle_1 = car_motorcycle.children.create(text: "自動車本体")
car_motorcycle_1.children.create([{text: "国内自動車本体"},{text: "外国自動車本体"}])
car_motorcycle_2 = car_motorcycle.children.create(text: "自動車タイヤ/ホイール")
car_motorcycle_2.children.create([{text: "タイヤ/ホイールセット"},{text: "タイヤ"},{text: "ホイール"},{text: "その他"}])
car_motorcycle_3 = car_motorcycle.children.create(text: "自動車パーツ")
car_motorcycle_3.children.create([{text: "サスペンション"},{text: "ブレーキ"},{text: "外装、エアロパーツ"},{text: "ライト"},{text: "内装品、シート"},{text: "ステアリング"},{text: "マフラー・排気系"},{text: "エンジン、過給器、冷却装置"},{text: "クラッチ、ミッション、駆動系"},{text: "電装品"},{text: "補強パーツ"},{text: "汎用パーツ"},{text: "外国自動車用パーツ"},{text: "その他"}])
car_motorcycle_4 = car_motorcycle.children.create(text: "自動車アクセサリー")
car_motorcycle_4.children.create([{text: "車内アクセサリー"},{text: "カーナビ"},{text: "カーオーディオ"},{text: "車外アクセサリー"},{text: "メンテナンス用品"},{text: "チャイルドシート"},{text: "ドライブレコーダー"},{text: "レーダー探知機"},{text: "カタログ/マニュアル"},{text: "セキュリティ"},{text: "ETC"},{text: "その他"}])
car_motorcycle_5 = car_motorcycle.children.create(text: "オートバイ車体")
car_motorcycle_5.children.create([{text: "すべて"}])
car_motorcycle_6 = car_motorcycle.children.create(text: "オートバイパーツ")
car_motorcycle_6.children.create([{text: "タイヤ"},{text: "マフラー"},{text: "エンジン、冷却装置"},{text: "カウル、フェンダー、外装"},{text: "サスペンション"},{text: "ホイール"},{text: "シート"},{text: "ブレーキ"},{text: "タンク"},{text: "ライト、ウィンカー"},{text: "チェーン、スプロケット、駆動系"},{text: "メーター"},{text: "電装系"},{text: "ミラー"},{text: "外国オートバイ用パーツ"},{text: "その他"}])
car_motorcycle_7 = car_motorcycle.children.create(text: "オートバイアクセサリー")
car_motorcycle_7.children.create([{text: "ヘルメット/シールド"},{text: "バイクウエア/装備"},{text: "アクセサリー"},{text: "メンテナンス"},{text: "カタログ/マニュアル"},{text: "その他"}])

# その他
others = Category.create(text: "その他")
others_1 = others.children.create(text: "まとめ売り")
others_1.children.create([{text: "すべて"}])
others_2 = others.children.create(text: "ペット用品")
others_2.children.create([{text: "ペットフード"},{text: "犬用品"},{text: "猫用品"},{text: "魚用品/水草"},{text: "小動物用品"},{text: "爬虫類/両生類用品"},{text: "かご/おり"},{text: "鳥用品"},{text: "虫類用品"},{text: "その他"}])
others_3 = others.children.create(text: "食品")
others_3.children.create([{text: "菓子"},{text: "米"},{text: "野菜"},{text: "果物"},{text: "調味料"},{text: "魚介類(加工食品)"},{text: "肉類(加工食品)"},{text: "その他 加工食品"},{text: "その他"}])
others_4 = others.children.create(text: "飲料/酒")
others_4.children.create([{text: "コーヒー"},{text: "ソフトドリンク"},{text: "ミネラルウォーター"},{text: "茶"},{text: "ウイスキー"},{text: "ワイン"},{text: "ブランデー"},{text: "焼酎"},{text: "日本酒"},{text: "ビール、発泡酒"},{text: "その他"}])
others_5 = others.children.create(text: "日用品/生活雑貨/旅行")
others_5.children.create([{text: "タオル/バス用品"},{text: "日用品/生活雑貨"},{text: "洗剤/柔軟剤"},{text: "旅行用品"},{text: "防災関連グッズ"},{text: "その他"}])
others_6 = others.children.create(text: "アンティーク/コレクション")
others_6.children.create([{text: "雑貨"},{text: "工芸品"},{text: "家具"},{text: "印刷物"},{text: "その他"}])
others_7 = others.children.create(text: "文房具/事務用品")
others_7.children.create([{text: "筆記具"},{text: "ノート/メモ帳"},{text: "テープ/マスキングテープ"},{text: "カレンダー/スケジュール"},{text: "アルバム/スクラップ"},{text: "ファイル/バインダー"},{text: "はさみ/カッター"},{text: "カードホルダー/名刺管理"},{text: "のり/ホッチキス"},{text: "その他"}])
others_8 = others.children.create(text: "事務/店舗用品")
others_8.children.create([{text: "オフィス用品一般"},{text: "オフィス家具"},{text: "店舗用品"},{text: "OA機器"},{text: "ラッピング/包装"},{text: "その他"}])
others_9 = others.children.create(text: "その他")
others_9.children.create([{text: "すべて"}])